"""Column custom_alias renamed for executable

Revision ID: 13a60b93107c
Revises: 84fc4efa4c5e
Create Date: 2024-01-23 17:44:01.956326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a60b93107c'
down_revision = '84fc4efa4c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('executable', sa.String(length=30), nullable=True))
        batch_op.drop_column('custom_alias')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_alias', sa.VARCHAR(length=30), nullable=True))
        batch_op.drop_column('executable')

    # ### end Alembic commands ###
