"""Column description addned

Revision ID: 84fc4efa4c5e
Revises: 2f999fe4ab23
Create Date: 2024-01-23 16:50:32.302395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84fc4efa4c5e'
down_revision = '2f999fe4ab23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
