"""Relationship

Revision ID: 8572f53071a2
Revises: bebec7d69a44
Create Date: 2024-01-16 20:09:45.265054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8572f53071a2'
down_revision = 'bebec7d69a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_column('type_install')
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=250), nullable=False))
        batch_op.add_column(sa.Column('type_install', sa.VARCHAR(length=60), nullable=False))

    # ### end Alembic commands ###
