"""Column installation_tip

Revision ID: e2b67444a95f
Revises: 8572f53071a2
Create Date: 2024-01-17 04:25:32.871609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b67444a95f'
down_revision = '8572f53071a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installation_tip', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_column('installation_tip')

    # ### end Alembic commands ###
